(() => {
  const app = document.querySelector('#app');
  const label = document.querySelector('#page-label');
  let view = 'overview', dayIndex = 0;
  const esc = v => String(v ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const date = v => { if (!v) return ''; const d = new Date(v); return Number.isNaN(d) ? v : d.toLocaleDateString('en-GB',{day:'numeric',month:'short',year:'numeric'}); };
  const data = TRIP_DATA;
  const dayNumber = d => d.day?.replace('Day ','') || '';
  const mapLink = (place, qualifier='Japan') => place ? `<a class="map-link" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(place+(qualifier?', '+qualifier:''))}" target="_blank" rel="noopener">${esc(place)} <span aria-hidden="true">↗</span></a>` : '';
  const facts = (items) => `<div class="facts">${items.filter(x=>x[1] !== null && x[1] !== undefined && x[1] !== '' && x[1] !== 'n/a').map(([k,v])=>`<div class="fact"><small>${esc(k)}</small>${esc(v)}</div>`).join('')}</div>`;
  const setView = next => {view=next; render(); window.scrollTo({top:0,behavior:'instant'});};
  function overview(){const hotelFor=name=>{const place=name.replace(/[🧳♨️]/g,'').trim();const stay=data.accommodations.find(x=>place.includes(x.city)||x.city.includes(place));return stay?`<span class="hotel">${esc(stay.hotel)}</span>`:''};const blocks=data.ganttBlocks.map(b=>{const isBase=b.start!==b.end&&!/Medan|Singapore/.test(b.name);return `<div class="gantt-block ${isBase?'is-base':''}" style="grid-column:${b.start+1}/${b.end+2};grid-row:${b.row-61}"><span>${esc(b.name)}</span>${isBase?hotelFor(b.name):''}</div>`}).join('');return `<p class="eyebrow">Offline reference · 18 Oct – 3 Nov 2026</p><h1>Route timeline</h1><p class="lede">This follows the workbook’s latest merged-cell timeline. Spans reflect the spreadsheet’s layout only, not invented travel durations. Base bars include the corresponding Japan hotel.</p><section class="gantt-wrap" aria-label="Trip timeline"><div class="gantt-head">${Array.from({length:17},(_,i)=>`<div><strong>Day ${i}</strong><small>${esc(date(data.timeline[i].date))}</small></div>`).join('')}</div><div class="gantt-grid">${blocks}</div></section><section class="section"><h2>Daily detail</h2><div class="day-strip">${data.days.map((x,i)=>`<button class="day-chip" data-day="${i}">Day ${dayNumber(x)}<br>${esc(x.location)}</button>`).join('')}</div></section>`}
  function days(){const d=data.days[dayIndex];return `<p class="eyebrow">Daily itinerary</p><div class="day-strip">${data.days.map((x,i)=>`<button class="day-chip ${i===dayIndex?'active':''}" data-day="${i}">Day ${dayNumber(x)}<br>${esc(x.date).slice(0,8)}</button>`).join('')}</div><h1>${mapLink(d.location)}</h1><p class="lede">${esc(d.day)} · ${esc(d.date)}</p><section class="section"><h2>Main places</h2><div class="places">${d.places.map(x=>`<div class="place-card"><h3>${mapLink(x.name)}</h3><div>${esc(x.description)}</div></div>`).join('')}</div></section><section class="section"><h2>Schedule</h2><div class="itinerary">${d.itinerary.map(x=>`<div class="itinerary-row"><div class="when">${esc(x.time)}</div><div><h3>${esc(x.activity)}</h3><p class="detail">${esc(x.details)}</p>${x.extra.map(v=>`<p class="detail">${esc(v)}</p>`).join('')}</div></div>`).join('')}</div></section><section class="section"><h2>Recommendations & options</h2>${d.recommendations.map(g=>`<div class="recommendation"><h3>${esc(g.category)}</h3>${g.items.map(x=>`<div class="recommendation-item"><div class="label">${esc(x.label)}</div><strong>${mapLink(x.name)}</strong><div class="detail">${esc(x.details)}</div>${x.extra.map(v=>`<div class="detail">${esc(v)}</div>`).join('')}</div>`).join('')}</div>`).join('')}</section>`}
  function transport(){let previous='';return `<p class="eyebrow">Transport</p><h1>Routes & tickets</h1><p class="lede">English and Japanese names stay together so the relevant details are ready at a station or bus terminal. Where the workbook supplies another timing, it is shown separately.</p><div class="summary">Total transport cost per pax <strong>¥${esc(data.transportSummary.totalPerPerson)}</strong>${facts(data.transportSummary.breakdown.map(x=>[x.method,'¥'+x.cost]))}</div>${data.transport.map(t=>{const e=t.english,j=t.japanese||{};const head=t.day!==previous ? (previous=t.day,`<div class="transport-day">${esc(t.day)}</div>`):'';return `${head}<article class="transport-card"><div class="route">${mapLink(e.from)} → ${mapLink(e.to)}</div>${(j.from||j.to||j.mode||j.line)?`<div class="jp">${esc(j.from)}${j.from&&j.to?' → ':''}${esc(j.to)}${j.mode?' · '+esc(j.mode):''}${j.line?' · '+esc(j.line):''}</div>`:''}${facts([['Service',e.mode],['Payment',e.payment],['Cost',e.cost!=null?'¥'+e.cost:null],['Departure',e.departure],['Arrival',e.arrival],['Duration',e.duration],['Line / direction',e.line]])}${t.alternative?`<div class="alternative"><strong>Alternative timing in the workbook</strong>${facts([['Departure',t.alternative.departure],['Arrival',t.alternative.arrival],['Duration',t.alternative.duration]])}</div>`:''}${e.notes?`<div class="note">${esc(e.notes)}</div>`:''}</article>`}).join('')}`}
  function stays(){return `<p class="eyebrow">Accommodation</p><h1>Stays</h1><div class="stays">${data.accommodations.map(x=>`<article class="panel"><div class="label">${esc(date(x.date))} · ${esc(x.city)} · ${esc(x.nights)} nights</div><h2>${mapLink(x.hotel)}</h2><div class="hotel-jp">${esc(x.japanese.hotel)}</div><p>${mapLink(x.address, '')}<br><span class="jp">${esc(x.japanese.address)}</span></p>${facts([['Phone',x.phone],['Japanese phone',x.japanese.phone],['Check-in / out',x.checkInOut],['Japanese',x.japanese.checkInOut],['Laundry',x.laundry],['Japanese laundry',x.japanese.laundry]])}</article>`).join('')}</div>`}
  function luggage(){return `<p class="eyebrow">Luggage forwarding</p><h1>Counter-ready details</h1><p class="lede">Show the Japanese destination details directly when arranging forwarding.</p><section class="section"><h2>Destinations</h2>${data.luggage.destinations.map(x=>`<article class="luggage-destination"><div class="label">${esc(x.city)} · ${esc(x.date)}</div><h2>${mapLink(x.hotel)}</h2><div class="show-text">${esc(x.hotelJapanese)}</div><p>${esc(x.recipient)}<br>${esc(x.recipientJapanese)}</p><p class="muted">${esc(x.checkIn)}<br>${esc(x.checkInJapanese)}</p><p>${mapLink(x.address, '')}<br><span class="show-text">${esc(x.addressJapanese)}</span><br>${esc(x.phone)} / ${esc(x.phoneJapanese)}</p></article>`).join('')}</section><section class="section"><h2>Required forwarding information</h2><div class="field-grid">${data.luggage.fields.map(x=>`<div class="field"><strong>${esc(x.field)}</strong><div class="show-text">${esc(x.japanese)}</div><div class="detail">${esc(x.example)}</div></div>`).join('')}</div></section><section class="section"><h2>Useful at the counter</h2>${data.luggage.phrases.map(x=>`<div class="phrase"><div class="english">${esc(x.english)}</div><div class="japanese">${esc(x.japanese)}</div><div class="roman">${esc(x.romanization)}</div></div>`).join('')}</section>`}
  function japanese(){const groups={};data.phrases.forEach(x=>(groups[x.category]??=[]).push(x));return `<p class="eyebrow">Japanese reference</p><h1>Show & say</h1><p class="lede">The original reference phrases, with Japanese kept large and romanization always present.</p><input class="phrase-filter" id="phrase-search" type="search" placeholder="Search English, Japanese, or romanization">${Object.entries(groups).map(([k,ps])=>`<section class="phrase-group" data-phrase-group><h2>${esc(k)}</h2>${ps.map(x=>`<article class="phrase" data-phrase="${esc([x.english,x.japanese,x.romanization,x.context].join(' ').toLowerCase())}"><div class="english">${esc(x.english)}</div><div class="japanese">${esc(x.japanese)}</div><div class="roman">${esc(x.romanization)}</div>${x.context?`<div class="detail">${esc(x.context)}</div>`:''}</article>`).join('')}</section>`).join('')}`}
  function render(){const titles={overview:'Trip overview',days:'Daily itinerary',transport:'Transport',stays:'Accommodation',luggage:'Luggage forwarding',japanese:'Japanese reference'};label.textContent=titles[view];app.innerHTML=({overview,days,transport,stays,luggage,japanese}[view])();document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{dayIndex=+b.dataset.day;setView('days')});const search=document.querySelector('#phrase-search');if(search)search.oninput=()=>{const q=search.value.toLowerCase();document.querySelectorAll('[data-phrase]').forEach(p=>p.hidden=!p.dataset.phrase.includes(q));document.querySelectorAll('[data-phrase-group]').forEach(g=>g.hidden=!Array.from(g.querySelectorAll('[data-phrase]')).some(p=>!p.hidden))};}
  document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view));render();
})();
